### PR TITLE
Fix slow imports

### PR DESCRIPTION
**Pull request by rossjones**
Move imports closer to use to speed up paster.

### CODE REVIEW

**Comment by davidread** [comment]
Would you mind submitting this to ckan/ckanext-spatial too? That will run tests on it and it makes it easier to diff our fork from the mainline.

**Comment by rossjones** [comment]
Tests on ckan/ckanext-spatial are broken.  amercader is pushing a config fix.

For some reason (probably because we've diverged a little) the speed-up is less dramatic, getting about 0.3s, but probably still enough.

**Comment by rossjones** [comment]
PR is at https://github.com/ckan/ckanext-spatial/pull/132

**Comment by rossjones** [comment]
PR seems to pass now upstream, so I'll merge it locally.

**Pull request merged**
